name = "Insomnia"
author = "dylanxyz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "397bd502b4bec93a445fda9e5fcdaf3269a2bc0b496ef1d688801faf244e443a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
